In [1]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
%pip install pandas scikit-learn joblib streamlit

Requirement already satisfied: pandas in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: scikit-learn in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.1)
Requirement already satisfied: joblib in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.6.0)
Requirement already satisfied: streamlit in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.65.0)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hp\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from joblib) (3.1.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.3.0)
Requirement already satisfied: click<9,>=7.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (8.5.0)
Requirement already satisfied: packaging>=20 in C:\Users\hp\AppData\Roaming\Python\Python314\site-packages (from streamlit) (26.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (12.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (7.36.2)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (25.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\hp\AppData\Roaming\Python\Python314\site-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (1.8.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.54.0)
Requirement already satisfied: httptools<1,>=0.6.3 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.9.0)
Requirement already satisfied: anyio<5,>=4.0.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (4.15.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<18,>=12.0.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (17.2)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: idna>=2.8 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from anyio<5,>=4.0.0->streamlit) (3.20)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.4)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.9.1)
Requirement already satisfied: six>=1.5 in C:\Users\hp\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:

data = {
    "area_sqft": [
        750, 850, 950, 1050, 1150,
        1250, 1350, 1450, 1550, 1650,
        1750, 1850, 2000, 2200, 2400
    ],
    "bedrooms": [
        2, 2, 2, 3, 3,
        3, 3, 3, 4, 4,
        4, 4, 4, 5, 5
    ],
    "bathrooms": [
        1, 1, 2, 2, 2,
        2, 3, 3, 3, 3,
        3, 4, 3, 4, 4
    ],
    "age_years": [
        18, 15, 12, 10, 9,
        7, 8, 6, 5, 4,
        3, 2, 6, 3, 1
    ],
    "price_lakh": [
        28, 33, 39, 45, 51,
        57, 62, 69, 75, 81,
        87, 95, 92, 110, 125
    ]
}

df = pd.DataFrame(data)

print("New House Dataset:")
display(df)

New House Dataset:

    area_sqft  bedrooms  bathrooms  age_years  price_lakh
0         750         2          1         18          28
1         850         2          1         15          33
2         950         2          2         12          39
3        1050         3          2         10          45
4        1150         3          2          9          51
5        1250         3          2          7          57
6        1350         3          3          8          62
7        1450         3          3          6          69
8        1550         4          3          5          75
9        1650         4          3          4          81
10       1750         4          3          3          87
11       1850         4          4          2          95
12       2000         4          3          6          92
13       2200         5          4          3         110
14       2400         5          4          1         125

In [4]:
X = df[["area_sqft", "bedrooms", "bathrooms", "age_years"]]
y = df["price_lakh"]

print("X aur y successfully ban gaye!")

X aur y successfully ban gaye!

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training houses:", len(X_train))
print("Testing houses:", len(X_test))

Training houses: 12
Testing houses: 3

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [7]:
import joblib

joblib.dump(model, "house_price_model.pkl")
print("Model saved successfully!")

Model saved successfully!

In [8]:

print("Dataset size:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDataset information:")
df.info()

model = LinearRegression()

model.fit(X_train, y_train)

print("House Price Prediction Model Trained Successfully!")

Dataset size: (15, 5)

Column names:
['area_sqft', 'bedrooms', 'bathrooms', 'age_years', 'price_lakh']

Missing values:
area_sqft     0
bedrooms      0
bathrooms     0
age_years     0
price_lakh    0
dtype: int64

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   area_sqft   15 non-null     int64
 1   bedrooms    15 non-null     int64
 2   bathrooms   15 non-null     int64
 3   age_years   15 non-null     int64
 4   price_lakh  15 non-null     int64
dtypes: int64(5)
memory usage: 732.0 bytes
House Price Prediction Model Trained Successfully!

In [9]:

predictions = model.predict(X_test)

results = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": predictions.round(2)
})

display(results)

   Actual Price  Predicted Price
0            81            80.99
1            95            93.00
2            28            23.45

In [10]:

mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("Mean Absolute Error:", round(mae, 2), "lakh")
print("R2 Score:", round(r2, 3))

Mean Absolute Error: 2.19 lakh
R2 Score: 0.99

In [11]:

new_house = pd.DataFrame({
    "area_sqft": [1900],
    "bedrooms": [4],
    "bathrooms": [3],
    "age_years": [4]
})

predicted_price = model.predict(new_house)

print(
    "Predicted House Price:",
    round(predicted_price[0], 2),
    "lakh"
)

Predicted House Price: 93.11 lakh

In [12]:

new_houses = pd.DataFrame({
    "area_sqft": [900, 1400, 1900, 2300],
    "bedrooms": [2, 3, 4, 5],
    "bathrooms": [1, 2, 3, 4],
    "age_years": [12, 7, 4, 2]
})

prices = model.predict(new_houses)

new_houses["predicted_price_lakh"] = prices.round(2)

display(new_houses)

   area_sqft  bedrooms  bathrooms  age_years  predicted_price_lakh
0        900         2          1         12                 35.27
1       1400         3          2          7                 64.95
2       1900         4          3          4                 93.11
3       2300         5          4          2                115.66